version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: phplabs
    container_name: phplabs-app
    restart: unless-stopped
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    networks:
      - phplabs

  db:
    image: postgres:alpine
    container_name: phplabs-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: docker
      SERVICE_TAGS: dev
      SERVICE_NAME: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker-compose/postgres:/docker-entrypoint-initdb.d
    networks:
      - phplabs
      
  nginx:
    image: nginx:1.23.3-alpine
    container_name: phplabs-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - phplabs
  
  composer:
    image: composer:latest
    container_name: phplabs-composer
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install
    networks:
      - phplabs

networks:
  phplabs:
    driver: bridge

