version: "3.7"
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: phplabs
    container_name: phplabs-app
    restart: unless-stopped
    working_dir: ${APP_PATH_CONTAINER}
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    networks:
      - phplabs

  db:
    image: mysql:8.0
    container_name: phplabs-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: ${DB_EMPTY_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${DB_RANDOM_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - phplabs
      
  nginx:
    image: nginx:1.23.3-alpine
    container_name: phplabs-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - phplabs
  
  composer:
    image: composer:latest
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install
    networks:
      - phplabs

networks:
  phplabs:
    driver: bridge

